version: '3'
services:
  web:
    build: .
    ports:
      - '80:80'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://acmadmin@postgres/acm
      DBHOST: postgres
      DBPORT: 5432
      DBNAME: acm
      DBUSERNAME: acmadmin
  postgres:
    image: postgres
    ports: 
      - '5432:5432'
    volumes: 
      - "datavolume:/var/lib/pgsql/data"
      - "./createtable.sh:/docker-entrypoint-initdb.d/createdb.sh"

volumes:
  datavolume:
